### ISSUE TITLE
For your consideration

### ISSUE THREAD

**Issue by South-Paw** [will-janz/warframe-item-list#4]
Hi! Awesome to see you've forked my repo and want to build off it 👍

As a suggestion, you may want to consider using my package as a dependency rather than trying to refactor/rewrite it with things like #1 #2 #3. If you use my package as a dep, then you can extend the objects to include `resources` or whatever else you'd like and simply re-export it or something.

If you do modify the files in here you will have to manually bring my upstream changes into your repo rather than just getting them for free with a `npm i` and a changed package version. Especially if you're going to fiddle with constant names, that's a world of pain your creating for yourself when updates happen and you don't want to rewrite what I just added to the upstream.

Alternatively, if you think there's ways that I can do stuff better upstream (in the parent repo and the npm package) - why not raise issues in my project so I can take them on for you (or you can fix them and propose a PR) and then you don't need to worry about them? Collaboration and team work are core concepts of OSS of course! 😉

Just some ideas and by all means you don't have to follow them - I just think you might as well save yourself some time knowing about these things before-hand ;)

Cheers,
Alex

**Comment by will-janz** [comment]
Hey Alex, thanks for posting this! My original goal was to do a PR for resources, but as I started digging and thinking, changes I'd want to make would be chaos from upstream (renaming, restructuring, adding attributes, etc.). 

I'm used to working with a closed source team, stepping into open source has been a bit scary. Thank you for being welcoming! I think it'd be simpler in the long run to submit issues and PRs.
